apiVersion: v1
kind: Service
metadata:
  labels:
    app: pos-service
  name: pos-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.139.149
  clusterIPs:
    - 10.103.139.149
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32679
      port: 5050
  selector:
    deployments: pos-service
  type: LoadBalancer
