apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  labels:
    app: sales-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deployments: sales-service
  template:
    metadata:
      labels:
        deployments: sales-service
    spec:
      containers:
        - name: sales-service
          image: sales:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
