apiVersion: v1
kind: Service
metadata:
  labels:
    app: sales-service
  name: sales-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.146.38
  clusterIPs:
    - 10.98.146.38
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31802
      port: 5001
  selector:
    deployments: sales-service
  type: LoadBalancer
