apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: product-service
  template:
    metadata:
      labels:
        apps: product-service
    spec:
      containers:
        - name: product-service
          image: product:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
