apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.185.240
  clusterIPs:
    - 10.99.185.240
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31399
      port: 5000
  selector:
    app: product-service
  type: LoadBalancer
